# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=128)),
                ('sub_distrito', models.CharField(max_length=128)),
                ('suco', models.CharField(max_length=128)),
                ('aldeia', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Potential',
        ),
    ]
