# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0002_auto_20170319_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('populations', models.CharField(max_length=128)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('descriptions', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='aldeia',
            name='suco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marobo.Suco'),
        ),
    ]
