# Generated by Django 2.0 on 2021-06-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0004_image_post_postimage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aldeia',
            name='suco',
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Aldeia',
        ),
        migrations.DeleteModel(
            name='Suco',
        ),
    ]
