# Generated by Django 2.2.24 on 2021-08-26 08:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0005_auto_20210608_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
