# Generated by Django 2.2.27 on 2022-02-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0007_postimage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
