# Generated by Django 2.2.27 on 2022-02-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_on',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_on',
        ),
    ]
