# Generated by Django 2.2.27 on 2022-02-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0010_auto_20220222_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
