# Generated by Django 2.2.27 on 2022-05-21 05:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0015_auto_20220305_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='postimage',
            name='descriptions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
