# Generated by Django 2.2.27 on 2022-03-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marobo', '0015_auto_20220302_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
